---
title: "Experience"
---

\  

### [Illumina, San Diego CA](https://www.illumina.com/)
### *Scientist II*
#### JAN 2023 - PRESENT
- Participate as part of the surface chemistry team
- Contribute to the development of new DNA sequencing technologies
- Take ownership of various projects
- Display proficiency, productivity, and effectiveness in lab
- Draw sound conclusions from complex experimental datasets
- Organize and lead team meetings
- Assist others with data analysis and script creation
- 2023 Illumina inventor award for submission of 3 invention disclosures and 1 patent application pending
- 2023 Advanced Science Illumina Innovation Poster Session: Presentation topic on flow cell surface functionalization

\  

### *Scientist I*
#### OCT 2022 - JAN 2023
- Designed complex experiments with appropriate controls
- Applied knowledge of a breadth of standard methods
- Wrote ideas and co-authored invention disclosures
- Collaborated with team members across disciplines
- Communicated effectively in many different environments

\  

### *Research Associate II*
#### MAY 2022 - OCT 2022
- Took independence in experiment planning/execution
- Interpreted results and suggested next steps
- Troubleshot problems in the laboratory
- Organized protocols, data, and results from experiments
- 2022 Advanced Science Illumina Innovation Poster Session: Presentation topic on flow cell surface functionalization

\  

### *Research Associate I*
#### OCT 2021 - APR 2022
- Executed planned laboratory experiments
- Took initiative for timely and quality work
- Learned how to prioritize projects
- Obtained guidance from other scientists

\  

### [Metis Online Flex Bootcamp](https://www.thisismetis.com/)
### *Data Scientist*
#### AUG 2021 - FEB 2022
- Completed a 24-week data science and engineering bootcamp focused on Python, statistics, linear algebra, data analysis, project pipelines, supervised and unsupervised machine learning, and visualization techniques
- Independently designed six end-to-end projects based on the following topics: Exploratory Data Analysis, Linear Regression and Web Scraping, Business Fundamentals, Machine Learning, Natural Language Processing, and Data Engineering
- Presented concepts and findings to data science professionals and peers of both technical and non-technical backgrounds
- Granted Diversity/Women in STEM scholarship towards tuition

\  

### [UC San Diego Recreation, La Jolla CA](https://recreation.ucsd.edu/)
### *Facility Supervisor*
#### SEPT 2018 - SEPT 2021
- Arranged for events, opened/closed the gym, and supervised sales staff
- Acted as a first responder in case of emergency in the building
- Served on the hiring committee, read applications, and conducted interviews
- Trained new employees and wrote the Facility Supervisor manuals
- Promoted to lead Facility Supervisor and scheduling lead in 2019
- Employee of the Month (Feb 2020), Employee of the Year (2019-2020)

\  

### *Recreation Experience Assistant*
#### SEPT 2017 - SEPT 2018
- Greeted patrons at the entrance to the facility
- Shared knowledge on all facilities and programs
- Rented equipment, sold memberships and classes
- Assisted with problem-solving and de-escalation

\  

### *Equipment Room / Sales Attendant*
#### OCT 2016 - SEPT 2017
- Rented equipment and lockers
- Sold memberships, classes, and merchandise
- Performed opening and closing procedures
- Reported issues or injuries to a supervisor

\  

### [UC San Diego Mathematics, La Jolla CA](https://math.ucsd.edu/)
### *Teaching Assistant*
#### SEPT 2019 - JUNE 2021
- Taught discussion sections and hosted office hours
- Proctored and graded midterms/final exams
- Served as the lead TA and organized schedules/grading
- Courses: Vector/Multivariable Calculus (MATH 20C), Integral Calculus (MATH 10B), Precalculus (MATH 3C), Probability/Statistics (MATH 11)

\  

### [Department of Pesticide Regulation /](https://www.cdpr.ca.gov/) [Cal EPA, Sacramento CA](https://calepa.ca.gov/)
### *Student Intern in the Human Health Assessment Branch*
#### SUMMER 2016, 2018
- Analyzed scientific documents and protocols
- Incorporated and evaluated a toxicology model in Microsoft Excel
- Performed sensitivity analyses and crafted reports with charts/graphs
- Researched and created a database of sources using the program EndNote

\  

### [Sacramento Zoological Society, Sacramento CA](https://www.saczoo.org/)
### *Summer Camp Teaching Assistant*
#### SUMMER 2016 - 2017
- Taught children (age 4-13) about biology and conservation
- Aided the teacher in designing and implementing lesson plans
- Supervised and instructed teenage camp counselors

\  

### *Summer Camp Counselor*
#### SUMMER 2011 - 2015
- Supervised hundreds of campers
- Followed directions from instructors
- Awards for initiative, leadership, and enthusiasm

\  

### [Private Math Tutor]()
#### SCHOLASTIC YEAR 2012 - 2015
- Assisted with homework and test preparation in Geometry and Algebra 2

\  

### [Temple Kol Shalom, El Dorado Hills CA](https://www.templekolshalom.org/)
### *Hebrew School Teacher*
#### SCHOLASTIC YEAR 2010 - 2014
- Taught children Hebrew prayers and about Jewish culture
- Guided students in preparation for their Bar/Bat Mitzvahs 
- Assisted with event/holiday preparations
